name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  ci:
    name: CI
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: '1.17.2'
        otp-version: '26.0'

    - name: Cache deps
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-deps-1.17.2-26.0-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-deps-1.17.2-26.0-

    - name: Cache _build
      uses: actions/cache@v4
      with:
        path: _build
        key: ${{ runner.os }}-build-1.17.2-26.0-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          ${{ runner.os }}-build-1.17.2-26.0-

    - name: Install dependencies
      run: mix deps.get

    - name: Check formatting
      run: mix format --check-formatted

    - name: Compile
      run: mix compile --warnings-as-errors

    - name: Run Credo
      run: mix credo --strict

    - name: Run tests
      run: mix test --trace
